version: "3.3"

services:
  db:
    image: postgres:11
    env_file: .env
    # environment:
      # - POSTGRES_DB=postgres
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  django_project:
    build: 
      context: .
    env_file: .env
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static:/project/static
      - .:/project
    #ports:
    #  - "8000:8000"
    depends_on:
      - db
    links:
      - db:db

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ../conf/nginx/conf.d:/etc/nginx/conf.d
      - static:/project/static
    depends_on:
      - django_project

volumes:
  .:
  postgres_data:
  static: